//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2Ledger_StockGasohol95__
    {
        public double SG_ORDER { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<double> DEBIT { get; set; }
        public Nullable<double> CREDIT { get; set; }
        public Nullable<double> BALANCE { get; set; }
        public string F7 { get; set; }
        public string F8 { get; set; }
    }
}
