//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class C3Recon_
    {
        internal int id;

        public double RECON_ORDER { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> PO { get; set; }
        public Nullable<double> Payment { get; set; }
        public Nullable<double> Invoice { get; set; }
        public Nullable<double> Shipment { get; set; }
        public string Truck { get; set; }
        public string PetrolType { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Agent { get; set; }
    }
}
