//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class C5Inventory_
    {
        internal int id;

        public double Inventory_ORDER { get; set; }
        public string Stock { get; set; }
        public Nullable<double> GASOHOL95 { get; set; }
        public Nullable<double> DIESEL { get; set; }
    }
}
