//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_3Recon__
    {
        public double RECON_ORDER { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> PO_ { get; set; }
        public Nullable<double> Payment_ { get; set; }
        public Nullable<double> Invoice_ { get; set; }
        public Nullable<double> Shipment_ { get; set; }
        public string Truck_ { get; set; }
        public string PetrolType { get; set; }
        public Nullable<double> Q_ty { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Agent { get; set; }
    }
}
