//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_4Income__
    {
        public double INCOME_ORDER { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<double> Sale_GAS95 { get; set; }
        public Nullable<double> Sale_Diesel { get; set; }
        public Nullable<double> Total_Sale { get; set; }
        public Nullable<double> COGS_GAS95 { get; set; }
        public Nullable<double> COGS_Diesel { get; set; }
        public Nullable<double> Total_COGS { get; set; }
        public Nullable<double> Gross_Profit { get; set; }
        public Nullable<double> Officer_Salary { get; set; }
        public Nullable<double> GateC_Salary { get; set; }
        public Nullable<double> Total_salary { get; set; }
        public Nullable<double> Utility_Expense { get; set; }
        public Nullable<double> Depreciation { get; set; }
        public Nullable<double> Net_Income_ { get; set; }
    }
}
