//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_6PO__
    {
        public double PO_ORDER { get; set; }
        public Nullable<double> PO_NO { get; set; }
        public Nullable<double> PAYMENT_NO { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> CUSTOMER_ID { get; set; }
        public string CUSTOMER { get; set; }
        public Nullable<double> TAX_PAYER_ID { get; set; }
        public string Truck { get; set; }
        public string ITEM { get; set; }
        public Nullable<double> Price_Litre { get; set; }
        public Nullable<double> Q_ty_Litre_ { get; set; }
        public Nullable<double> Amount { get; set; }
    }
}
