//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_7invoice__
    {
        internal int id;

        public double INVOICE_ORDER_ { get; set; }
        public string COMPANY_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string MAIL { get; set; }
        public string TEL { get; set; }
        public Nullable<double> INVOICE_NO { get; set; }
        public Nullable<double> PO_NO { get; set; }
        public Nullable<double> PAYMENT_NO { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<double> CUSTOMER_ID { get; set; }
        public string CUSTOMER { get; set; }
        public Nullable<double> TAX_PAYER_ID { get; set; }
        public Nullable<System.DateTime> DATE1 { get; set; }
        public Nullable<double> FILL_TIME_MIN { get; set; }
        public string ITEM { get; set; }
        public Nullable<double> Price_Litre { get; set; }
        public Nullable<double> Q_ty_Litre_ { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> val7_ { get; set; }
        public Nullable<double> GRAND_TOTAL { get; set; }
    }
}
