//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BAY_STATION__
    {
        internal int id;

        public double Bay_ID { get; set; }
        public Nullable<double> Gas_ID { get; set; }
        public string BayName { get; set; }
    }
}
