//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_JOUNAL_TRANSECTION__
    {
        internal int id;

        public string Fianance_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string TransName { get; set; }
        public string TransType { get; set; }
        public string TransValue { get; set; }
    }
}
