//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Capston2Entities8 : DbContext
    {
        public Capston2Entities8()
            : base("name=Capston2Entities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C1Jounal_> C1Jounal_ { get; set; }
        public virtual DbSet<C2Ledeger_AR__> C2Ledeger_AR__ { get; set; }
        public virtual DbSet<C2Ledger_AP__> C2Ledger_AP__ { get; set; }
        public virtual DbSet<C2Ledger_Cash__> C2Ledger_Cash__ { get; set; }
        public virtual DbSet<C2Ledger_StockDeisel__> C2Ledger_StockDeisel__ { get; set; }
        public virtual DbSet<C2Ledger_StockGasohol95__> C2Ledger_StockGasohol95__ { get; set; }
        public virtual DbSet<C3Recon_> C3Recon_ { get; set; }
        public virtual DbSet<C_3Recon__> C_3Recon__ { get; set; }
        public virtual DbSet<C4Income_> C4Income_ { get; set; }
        public virtual DbSet<C_4Income__> C_4Income__ { get; set; }
        public virtual DbSet<C5Inventory_> C5Inventory_ { get; set; }
        public virtual DbSet<C_5Inventory__> C_5Inventory__ { get; set; }
        public virtual DbSet<C6PO_> C6PO_ { get; set; }
        public virtual DbSet<C_6PO__> C_6PO__ { get; set; }
        public virtual DbSet<C7invoice_> C7invoice_ { get; set; }
        public virtual DbSet<C_7invoice__> C_7invoice__ { get; set; }
        public virtual DbSet<C_BAY_STATION__> C_BAY_STATION__ { get; set; }
        public virtual DbSet<CUSTOMER_> CUSTOMER_ { get; set; }
        public virtual DbSet<GAS_> GAS_ { get; set; }
        public virtual DbSet<GASNEW_> GASNEW_ { get; set; }
        public virtual DbSet<Gen_Journal_> Gen_Journal_ { get; set; }
        public virtual DbSet<INVOICE_> INVOICE_ { get; set; }
        public virtual DbSet<C_JOUNAL_TRANSECTION__> C_JOUNAL_TRANSECTION__ { get; set; }
        public virtual DbSet<PAYMENT_> PAYMENT_ { get; set; }
        public virtual DbSet<PURCHEASE_> PURCHEASE_ { get; set; }
        public virtual DbSet<C_SALE_OFFICE__> C_SALE_OFFICE__ { get; set; }
        public virtual DbSet<STAFF_> STAFF_ { get; set; }
        public virtual DbSet<TRUCK_> TRUCK_ { get; set; }
        public virtual DbSet<WEIGHT_> WEIGHT_ { get; set; }
    }
}
