//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class GASNEW_
    {
        internal int id;

        public double GasID { get; set; }
        public string GasName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> DIESEL_Cost { get; set; }
        public Nullable<double> DIESEL_Price { get; set; }
        public Nullable<double> GASOHOL95_Cost { get; set; }
        public Nullable<double> GASOHOL95_Price { get; set; }
        public string F8 { get; set; }
        public string F9 { get; set; }
        public string F10 { get; set; }
    }
}
