//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE_
    {
        public double Invoice_ID { get; set; }
        public Nullable<double> PO_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<double> DEL_NUM { get; set; }
        public Nullable<double> CustomerID { get; set; }
        public Nullable<double> Pay_ID__Address_ { get; set; }
        public Nullable<double> Filling_time { get; set; }
        public string F8 { get; set; }
        public Nullable<double> Amount_Filling_Volume { get; set; }
        public Nullable<double> Price_per_volume { get; set; }
        public Nullable<double> F11 { get; set; }
        public Nullable<double> Total_Price__Baht_ { get; set; }
        public Nullable<double> F13 { get; set; }
    }
}
