//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_
    {
        internal int id;

        public double Pay_ID__Address_ { get; set; }
        public Nullable<double> Card_ID { get; set; }
        public Nullable<double> CustomerID { get; set; }
        public string Company_Name { get; set; }
    }
}
