//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURCHEASE_
    {
        public double PO_ID { get; set; }
        public Nullable<double> SERVICE_ID { get; set; }
        public Nullable<double> GAS_ID { get; set; }
        public Nullable<double> BAY_ID { get; set; }
        public Nullable<double> TRUCK_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string WeightID { get; set; }
        public Nullable<System.DateTime> FILL_START_TIME { get; set; }
        public Nullable<System.DateTime> FILL_END_TIME { get; set; }
        public Nullable<System.DateTime> TIME_DIF { get; set; }
        public Nullable<double> FILLINGTIME { get; set; }
        public Nullable<double> Volume___200_ { get; set; }
        public string Status { get; set; }
    }
}
