//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_
    {
        internal int id;

        public double Staff_ID { get; set; }
        public string Username { get; set; }
        public Nullable<double> UserPassword { get; set; }
        public string Firstname_Lastname { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BOD { get; set; }
        public Nullable<double> Address { get; set; }
        public string Phone { get; set; }
        public string Position { get; set; }
        public string F10 { get; set; }
        public string F11 { get; set; }
        public string F12 { get; set; }
        public string F13 { get; set; }
        public string F14 { get; set; }
        public string F15 { get; set; }
        public string F16 { get; set; }
        public string F17 { get; set; }
        public string F18 { get; set; }
    }
}
