//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRUCK_
    {
        internal int id;

        public double Truck_ID { get; set; }
        public Nullable<double> Customer_ID { get; set; }
        public string Driver_Firstname_Lastname { get; set; }
        public string VEHICLE_NUMBER { get; set; }
        public string F5 { get; set; }
        public string F6 { get; set; }
        public string F7 { get; set; }
        public string Company_Name { get; set; }
        public Nullable<double> shipping_Address { get; set; }
    }
}
