//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEIGHT_
    {
        internal int id;

        public string WeightID { get; set; }
        public string QUEUE { get; set; }
        public Nullable<System.DateTime> TIME_In { get; set; }
        public string TIME_Out { get; set; }
    }
}
